### ISSUE TITLE
Update freezed dependencies

### ISSUE THREAD

**Issue by apgapg** [FieldAssist/fa_flutter_core#11]
Freezed is now 1.x.y+

**Comment by Ritsz123** [comment]
@FieldAssist/fa-flutter lets take this up and remove `freezed` dependency from other projects it causing a lot of problems...

**Comment by singhtaranjeet** [comment]
@Ritsz123 what kind of conflicts?

**Comment by Ritsz123** [comment]
@singhtaranjeet conflicts in place where we need to update dependencies

**Comment by singhtaranjeet** [comment]
We've added freezed as dev dependency and dev dependencies are project specific.

**Comment by Ritsz123** [comment]
@singhtaranjeet although freezed is added as dev dependency we still have freezed_annotation as a regular dependency

**Comment by singhtaranjeet** [comment]
@Ritsz123 Yes, we can remove direct dependency freezed_annotation and use it via flutter_core
